name: Tests
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python_version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
        install_xdist: [ true, false ]
    concurrency:
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.os }}-${{ matrix.python_version }}-$${{ matrix.install_xdist }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install package dependencies
        run: pip install .[test]

      - name: Maybe install pytest-xdist
        if: ${{ matrix.install_xdist }}
        run: pip install pytest-xdist

      - name: Show versions
        run: pip freeze

      - name: Run tests
        run: pytest tests/
